<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; The Small-n Methods Literature: A Bibliometric Map – Small-n Approaches to Impact Evaluation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-counterfactual.html" rel="next">
<link href="./03-eight-logics.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9ce26e16e0ee9b258b6d4ad01075dada.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-introduction.html">Foundations</a></li><li class="breadcrumb-item"><a href="./appendix-bibliometric.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Small-n Methods Literature: A Bibliometric Map</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Small-n Approaches to Impact Evaluation</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Small-n approaches to impact evaluation</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-defining-small-n.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Defining Small-n</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-eight-logics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Causal Reasoning in Small-n Evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-bibliometric.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Small-n Methods Literature: A Bibliometric Map</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Methods for Small-n Causal Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-counterfactual.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Counterfactual Designs for Small Samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-configurational.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Configurational Approaches</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-process-tracing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Process Tracing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-contribution-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Contribution Analysis and Theory of Change</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-realist-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Realist Evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Diagnostic Approaches</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-participatory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Participatory Approaches to Evidence About Change</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Computational Simulation as Complement to Small-n Designs</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Integration and Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-decision-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">A Decision Framework for Method Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Integrating Methods and Causal Claims</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-quality-standards.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Bias, Transparency, and Quality Standards</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Small-n Evidence in Policy and Development Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-eipm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Small-n Methods and Evidence-Informed Policymaking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-commissioning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Commissioning Small-n Evaluations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-translating.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Translating Small-n Evidence for Policy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-constrained.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Small-n Evidence in Constrained Settings</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Synthesis and Conclusion</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evidence-synthesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Evidence Synthesis of Small-n Studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Small-n Evaluation as Causal Inquiry</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-supporting-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Supporting simulation literature</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-method-selection-aid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Method-selection aid for small-n evaluation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#sec-methods-questions" id="toc-sec-methods-questions" class="nav-link active" data-scroll-target="#sec-methods-questions"><span class="header-section-number">5.1</span> Questions and units of analysis</a></li>
  <li><a href="#sec-methods-search" id="toc-sec-methods-search" class="nav-link" data-scroll-target="#sec-methods-search"><span class="header-section-number">5.2</span> Search strategy</a></li>
  <li><a href="#sec-methods-prisma" id="toc-sec-methods-prisma" class="nav-link" data-scroll-target="#sec-methods-prisma"><span class="header-section-number">5.3</span> Corpus construction and validation</a></li>
  <li><a href="#sec-methods-analyses" id="toc-sec-methods-analyses" class="nav-link" data-scroll-target="#sec-methods-analyses"><span class="header-section-number">5.4</span> Analyses and claim boundaries</a></li>
  <li><a href="#sec-methods-results" id="toc-sec-methods-results" class="nav-link" data-scroll-target="#sec-methods-results"><span class="header-section-number">5.5</span> Results</a></li>
  <li><a href="#sec-methods-reproducibility" id="toc-sec-methods-reproducibility" class="nav-link" data-scroll-target="#sec-methods-reproducibility"><span class="header-section-number">5.6</span> Reproducibility</a></li>
  <li><a href="#sec-methods-limits" id="toc-sec-methods-limits" class="nav-link" data-scroll-target="#sec-methods-limits"><span class="header-section-number">5.7</span> Limitations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-introduction.html">Foundations</a></li><li class="breadcrumb-item"><a href="./appendix-bibliometric.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Small-n Methods Literature: A Bibliometric Map</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-methods-appendix" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Small-n Methods Literature: A Bibliometric Map</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The chapters that follow describe eight components of causal reasoning and the method families built on them. This chapter maps how the corresponding terms appear in the indexed research literature: how many publications name each method, where that literature concentrates by discipline and country, how it has changed over time, and how far the labelled families overlap. The map describes how named small-n methods appear in the indexed literature and helps identify publications for closer review in the method chapters. It does not treat the number of publications as a measure of methodological quality, evaluator capability, or adoption in evaluation practice.</p>
<p>The analysis distinguishes four records of evidence. The <strong>raw discovery archive</strong> contains every configured expression found in a title or abstract. The <strong>core-method corpus</strong> contains labels suitable for comparative bibliometric analysis. The <strong>supporting-simulation corpus</strong> covers agent-based modelling and system dynamics separately. The <strong>evaluation and development subsets</strong> contain records coded as applications after method relevance has been assessed. Theory of change remains in the discovery archive as a conceptual precursor; it is not counted as a method.</p>
<section id="sec-methods-questions" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-methods-questions"><span class="header-section-number">5.1</span> Questions and units of analysis</h2>
<p>The raw archive supports retrieval and audit. The core-method corpus supports cautious description of named-method publication counts, disciplinary and venue distributions, authorship, institutional location, and co-mention between the core method families. Its principal unit is a unique OpenAlex work–method pair. A publication that names two methods contributes one pair to each method, while family totals deduplicate the work within each family.</p>
<p>The validated subset addresses two narrower questions: whether the intended method was used in an evaluation of an identifiable intervention, programme, policy, reform, service, or implementation effort; and whether that evaluation concerns international development. The unit remains the work–method pair because one publication may apply one named method while mentioning another only in discussion. A development application has either an LMIC setting or an explicit development purpose.</p>
</section>
<section id="sec-methods-search" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-methods-search"><span class="header-section-number">5.2</span> Search strategy</h2>
<p>OpenAlex was queried on 2 August 2026 through the <code>works</code> endpoint <span class="citation" data-cites="openalex2026">(<a href="references.html#ref-openalex2026" role="doc-biblioref">OpenAlex, 2026</a>)</span> for publications dated 2000–2025. Each search used the method expressions in <a href="#tbl-corpus-terms" class="quarto-xref">Table&nbsp;<span>5.1</span></a>. OpenAlex searches titles, abstracts, and indexed full text to retrieve candidate records. The local filter then required a configured expression to appear in the title or abstract. This second step fixes the observable field on which inclusion depends and avoids treating a full-text reference as evidence that the publication discusses the method.</p>
<div id="tbl-corpus-terms" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-corpus-terms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Search coverage aligned with the book’s causal-method families, supporting models, and contextual precursor. Exact variants and regular expressions are recorded in <code>bibliometric_config.py</code>.
</figcaption>
<div aria-describedby="tbl-corpus-terms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Method family</th>
<th>Method or framework</th>
<th>Bibliometric treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Counterfactual designs</td>
<td>Single-case experimental design; N-of-1 trial; randomisation inference</td>
<td>Methods</td>
</tr>
<tr class="even">
<td>Configurational approaches</td>
<td>Qualitative comparative analysis; coincidence analysis</td>
<td>QCA is in comparative counts; coincidence analysis requires record-level intent screening</td>
</tr>
<tr class="odd">
<td>Generative and mechanistic approaches</td>
<td>Process tracing; contribution analysis; realist evaluation; general elimination methodology</td>
<td>Contribution analysis requires record-level intent screening; the other labels remain in comparative counts</td>
</tr>
<tr class="even">
<td>Contextual precursor</td>
<td>Theory of change</td>
<td>Discovery archive only; excluded from bibliometric counts and comparisons</td>
</tr>
<tr class="odd">
<td>Diagnostic approaches</td>
<td>Bayesian process tracing</td>
<td>Method of diagnostic updating</td>
</tr>
<tr class="even">
<td>Participatory and agency-based approaches</td>
<td>Most Significant Change; outcome harvesting</td>
<td>Outcome harvesting is in comparative counts; Most Significant Change requires record-level intent screening</td>
</tr>
<tr class="odd">
<td>Supporting simulation</td>
<td>Agent-based modelling; system dynamics</td>
<td>Separate supporting-literature appendix; excluded from comparative method counts</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Cursor pagination continues until OpenAlex returns the complete result set. The analysis does not impose a common maximum per method. A testing cap is available in the retrieval script, but the resulting manifest is marked incomplete and downstream scripts reject it by default. Current OpenAlex access requires an API key; the script reads it from the environment or a one-line file outside the repository and does not print or copy it into the output.</p>
<p>The complete retrieval returned 318,950 candidate method–work records. Of these, 281,736 had an eligible publication type. Exact title-and-abstract matching retained 58,328 method–work pairs, representing 57,840 unique works in the raw discovery archive. The comparative core-method corpus contains 18,687 pairs and 18,520 unique works. Supporting simulation contains 29,325 pairs, theory of change 6,370 pairs, and the three labels requiring record-level intent screening 3,946 pairs; none enters the comparative counts. These categories overlap at the work level, so their unique-work totals cannot be added. <a href="#tbl-corpus-yield" class="quarto-xref">Table&nbsp;<span>5.2</span></a> shows the search yield and treatment of each expression.</p>
<div id="tbl-corpus-yield" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-corpus-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: Yield of the OpenAlex search and exact title-and-abstract filter. Counts are method–work pairs; a work can appear under more than one configured expression.
</figcaption>
<div aria-describedby="tbl-corpus-yield-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Method or framework</th>
<th>Treatment</th>
<th style="text-align: right;">Candidate records</th>
<th style="text-align: right;">Title/abstract pairs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Single-case experimental design</td>
<td>Core method</td>
<td style="text-align: right;">4,149</td>
<td style="text-align: right;">1,356</td>
</tr>
<tr class="even">
<td>N-of-1 trial</td>
<td>Core method</td>
<td style="text-align: right;">4,021</td>
<td style="text-align: right;">767</td>
</tr>
<tr class="odd">
<td>Randomisation inference</td>
<td>Core method</td>
<td style="text-align: right;">2,568</td>
<td style="text-align: right;">186</td>
</tr>
<tr class="even">
<td>Qualitative comparative analysis</td>
<td>Core method</td>
<td style="text-align: right;">24,996</td>
<td style="text-align: right;">8,270</td>
</tr>
<tr class="odd">
<td>Coincidence analysis</td>
<td>Discovery and validated applications only; excluded from comparative surface counts</td>
<td style="text-align: right;">1,723</td>
<td style="text-align: right;">323</td>
</tr>
<tr class="even">
<td>Process tracing</td>
<td>Core method; intent screen required</td>
<td style="text-align: right;">17,174</td>
<td style="text-align: right;">4,482</td>
</tr>
<tr class="odd">
<td>Contribution analysis</td>
<td>Discovery and validated applications only; excluded from comparative surface counts</td>
<td style="text-align: right;">10,791</td>
<td style="text-align: right;">1,715</td>
</tr>
<tr class="even">
<td>Realist evaluation</td>
<td>Core method</td>
<td style="text-align: right;">26,468</td>
<td style="text-align: right;">3,524</td>
</tr>
<tr class="odd">
<td>General elimination methodology</td>
<td>Core method</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td>Theory of change</td>
<td>Contextual precursor</td>
<td style="text-align: right;">55,294</td>
<td style="text-align: right;">6,370</td>
</tr>
<tr class="odd">
<td>Bayesian process tracing</td>
<td>Core method</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="even">
<td>Most Significant Change</td>
<td>Discovery and validated applications only; excluded from comparative surface counts</td>
<td style="text-align: right;">47,766</td>
<td style="text-align: right;">1,908</td>
</tr>
<tr class="odd">
<td>Outcome harvesting</td>
<td>Core method</td>
<td style="text-align: right;">462</td>
<td style="text-align: right;">64</td>
</tr>
<tr class="even">
<td>Agent-based modelling</td>
<td>Supporting simulation</td>
<td style="text-align: right;">91,086</td>
<td style="text-align: right;">22,185</td>
</tr>
<tr class="odd">
<td>System dynamics</td>
<td>Supporting simulation</td>
<td style="text-align: right;">32,318</td>
<td style="text-align: right;">7,140</td>
</tr>
<tr class="even">
<td><strong>Raw discovery archive</strong></td>
<td><strong>All configured expressions</strong></td>
<td style="text-align: right;"><strong>318,950</strong></td>
<td style="text-align: right;"><strong>58,328</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The raw JSONL files retain the OpenAlex work identifier, DOI, publication date and type, title, abstract index, citation count, language, primary topic, source, authorships, author identifiers, and institutional identifiers. Nested metadata are retained at retrieval because author names alone cannot support disambiguation or institutional analysis.</p>
</section>
<section id="sec-methods-prisma" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-methods-prisma"><span class="header-section-number">5.3</span> Corpus construction and validation</h2>
<p>The automated filter retains articles, reviews, books, book chapters, reports, dissertations, and preprints. It does not exclude records on the basis of language or OpenAlex topic. Language is incomplete in some OpenAlex records, and a common topic exclusion would affect the method families unevenly. Computer-science classifications, for example, include relevant agent-based models, while agricultural and health classifications may contain development applications.</p>
<p>Records are deduplicated by OpenAlex work identifier within each method. Search variants such as British and American spellings therefore do not produce additional observations. The processed files preserve separate tables for works, work–method pairs, and author–institution–work relations. This structure allows method counts to use unique works while authorship analyses use stable identifiers and can apply fractional credit.</p>
<p>Keyword screening marked 28,687 possible evaluation applications; it did not determine final inclusion in the application subset. A reproducible sample of 1,242 records was drawn within each expression and separately for records with and without evaluation-related terms. A balanced first-stage sample of 273 records and a targeted second-stage review of 255 records, including 40 simulation records, have been coded by a reference reviewer. The screen records method relevance, evaluation application, and development application. Records marked as repeated or overlapping are held outside the denominator until their duplicate status is resolved.</p>
<p>The completed review shows why some exact phrases cannot be used as comparative method counts. <em>Coincidence analysis</em> also retrieves event-coincidence and detector procedures in climate science and physics. <em>Contribution analysis</em> retrieves engineering, source-apportionment, and economic decomposition methods. <em>Most Significant Change</em> often describes an outcome or ordinary comparative language rather than the participatory evaluation approach. These records remain useful for discovery, but the three labels are excluded from comparative surface counts. An intended-method record can still enter the evaluation or development subset after screening.</p>
<p>The workflow is described as an automated bibliometric filter with manual validation. It is not a PRISMA screening process or a systematic review of evaluation studies. A later systematic review could use the validated application subset as one source, but it would require additional databases, grey-literature searches, full-text eligibility assessment, and method-specific quality appraisal.</p>
</section>
<section id="sec-methods-analyses" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-methods-analyses"><span class="header-section-number">5.4</span> Analyses and claim boundaries</h2>
<p>Publication trends and co-mentions use the comparative core-method records only. Labels with materially different technical meanings are excluded even when they are retained in the raw archive. Changes in counts may reflect publication volume, terminology, indexing coverage, or attention to a method. They do not establish how often evaluators use the method. Supporting simulation is reported separately, and theory of change is not reported as a method count.</p>
<p>Co-mention counts identify works whose title or abstract names methods from two families. The analysis reports both counts and a Jaccard coefficient because the family corpora differ greatly in size. Co-mention does not show that the methods were integrated in the same evaluation; the full text must be examined before making that claim.</p>
<p>Bayesian process tracing contains the phrase <em>process tracing</em>. This nested label is excluded from the family co-mention analysis so that one expression is not counted as evidence that diagnostic and generative methods appear together.</p>
<p>Disciplinary and venue analyses use the core-method surface corpus rather than an equal quota of highly cited publications. OpenAlex’s primary topic is reported as an algorithmic classification, not the publication’s definitive disciplinary location. Citation-selected subsets may still be used to identify prominent publications for reading, but they are not used to describe the structure of the field.</p>
<p>Authorship analyses aggregate by OpenAlex author identifier. Both full and fractional work counts are reported because large teams otherwise receive disproportionate weight. Institutional and geographic summaries use the affiliations attached to each authorship and retain missing affiliations. A high count means that an author appears frequently on publications in the corpus; it does not by itself establish a contribution to method development.</p>
</section>
<section id="sec-methods-results" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-methods-results"><span class="header-section-number">5.5</span> Results</h2>
<p>The results below describe the comparative core-method corpus defined above: 18,687 method–work pairs across nine methods in five families, plus the three intent-screened labels (coincidence analysis, contribution analysis, Most Significant Change) and supporting simulation reported separately. Each result is a description of indexed, title-and-abstract-matched terminology. None establishes how often a method is used in evaluation practice, and each method chapter in Part II repeats the relevant caution before using these counts.</p>
<section id="where-the-literature-concentrates" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="where-the-literature-concentrates"><span class="header-section-number">5.5.1</span> Where the literature concentrates</h3>
<p><a href="#fig-method-subfield-shares" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> reports each method’s distribution across OpenAlex primary subfields. The families do not share a common home discipline. Qualitative comparative analysis and process tracing concentrate in Sociology and Political Science and in Political Science and International Relations; randomisation inference concentrates overwhelmingly in Statistics and Probability (114 of 186 pairs, 61 per cent); single-case experimental design and N-of-1 trial concentrate in clinical and psychological subfields (Developmental and Educational Psychology, Clinical Psychology, Cognitive Neuroscience for SCED; Statistics and Probability, Psychiatry and Mental Health, Genetics for N-of-1 trials); and realist evaluation concentrates in General Health Professions (595 of 3,524 pairs). Outcome harvesting, the smallest core-method corpus, is too thin to support a comparable subfield claim beyond noting its concentration in Management Science and Operations Research and General Agricultural and Biological Sciences.</p>
<div id="fig-method-subfield-shares" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Heatmap of the share of each method's surface-mention corpus by OpenAlex primary subfield. Randomisation inference is concentrated in Statistics and Probability; qualitative comparative analysis and process tracing concentrate in Sociology and Political Science; realist evaluation concentrates in General Health Professions; single-case experimental design and N-of-1 trial concentrate in psychology and clinical subfields.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-method-subfield-shares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/bibliometrics_intent_v2/fig-method-subfield-shares.png" class="img-fluid figure-img" alt="Heatmap of the share of each method's surface-mention corpus by OpenAlex primary subfield. Randomisation inference is concentrated in Statistics and Probability; qualitative comparative analysis and process tracing concentrate in Sociology and Political Science; realist evaluation concentrates in General Health Professions; single-case experimental design and N-of-1 trial concentrate in psychology and clinical subfields.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-method-subfield-shares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Share of each method’s surface-mention corpus by OpenAlex primary subfield, 2000–2025. Darker cells indicate a larger share of that method’s own corpus in the named subfield; rows do not sum to a common total across methods. Data: OpenAlex, retrieved 2 August 2026.
</figcaption>
</figure>
</div>
<p>The disciplinary split matters for how a method chapter should be read. A reader trained in health sciences will find single-case experimental design and realist evaluation close to a familiar literature, while qualitative comparative analysis and process tracing sit closer to political science and management research. The book’s causal-reasoning framework in <a href="03-eight-logics.html" class="quarto-xref"><span>Chapter 4</span></a> is written to hold across this disciplinary split; the terminology in the source literatures does not.</p>
</section>
<section id="publication-trends-by-family" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="publication-trends-by-family"><span class="header-section-number">5.5.2</span> Publication trends by family</h3>
<p>Publication counts naming each family’s methods have grown over 2000–2025, but from very different bases and at different rates. <a href="#fig-counterfactual-designs-trends" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>, <a href="#fig-configurational-approaches-trends" class="quarto-xref">Figure&nbsp;<span>5.3</span></a>, <a href="#fig-generative-trends" class="quarto-xref">Figure&nbsp;<span>5.4</span></a>, <a href="#fig-diagnostic-approaches-trends" class="quarto-xref">Figure&nbsp;<span>5.5</span></a>, and <a href="#fig-participatory-and-agency-based-approaches-trends" class="quarto-xref">Figure&nbsp;<span>5.6</span></a> show the year-by-year surface-mention count for each family; <a href="appendix-supporting-simulation.html" class="quarto-xref"><span>Chapter 23</span></a> reports the same for agent-based modelling and system dynamics, kept separate from the comparative corpus because those traditions are supporting models rather than evaluation methods. A rising count reflects rising use of the terminology in an indexed title or abstract. It does not by itself indicate rising use of the method in evaluation, since indexing coverage and disciplinary output have also grown over the period.</p>
<div id="fig-counterfactual-designs-trends" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line chart of single-case experimental design, N-of-1 trial, and randomisation inference surface-mention counts by year, 2000-2025, each showing an upward trend from a low base.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-counterfactual-designs-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/bibliometrics_intent_v2/fig-counterfactual-designs-trends.png" class="img-fluid figure-img" alt="Line chart of single-case experimental design, N-of-1 trial, and randomisation inference surface-mention counts by year, 2000-2025, each showing an upward trend from a low base.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-counterfactual-designs-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Counterfactual designs: surface-mention publications by year, 2000–2025. Data: OpenAlex, retrieved 2 August 2026.
</figcaption>
</figure>
</div>
<div id="fig-configurational-approaches-trends" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line chart of qualitative comparative analysis surface-mention counts by year, 2000-2025, showing sustained growth from the mid-2000s.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-configurational-approaches-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/bibliometrics_intent_v2/fig-configurational-approaches-trends.png" class="img-fluid figure-img" alt="Line chart of qualitative comparative analysis surface-mention counts by year, 2000-2025, showing sustained growth from the mid-2000s.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-configurational-approaches-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Configurational approaches: surface-mention publications by year, 2000–2025. Data: OpenAlex, retrieved 2 August 2026.
</figcaption>
</figure>
</div>
<div id="fig-generative-trends" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line chart of process tracing, realist evaluation, and general elimination methodology surface-mention counts by year, 2000-2025.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-generative-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/bibliometrics_intent_v2/fig-generative-and-mechanistic-approaches-trends.png" class="img-fluid figure-img" alt="Line chart of process tracing, realist evaluation, and general elimination methodology surface-mention counts by year, 2000-2025.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-generative-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Generative and mechanistic approaches: surface-mention publications by year, 2000–2025. Data: OpenAlex, retrieved 2 August 2026.
</figcaption>
</figure>
</div>
<div id="fig-diagnostic-approaches-trends" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line chart of Bayesian process tracing surface-mention counts by year, 2000-2025, a small and irregular series.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagnostic-approaches-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/bibliometrics_intent_v2/fig-diagnostic-approaches-trends.png" class="img-fluid figure-img" alt="Line chart of Bayesian process tracing surface-mention counts by year, 2000-2025, a small and irregular series.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostic-approaches-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Diagnostic approaches: surface-mention publications by year, 2000–2025. Data: OpenAlex, retrieved 2 August 2026.
</figcaption>
</figure>
</div>
<div id="fig-participatory-and-agency-based-approaches-trends" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line chart of outcome harvesting surface-mention counts by year, 2000-2025, a small series.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-participatory-and-agency-based-approaches-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/bibliometrics_intent_v2/fig-participatory-and-agency-based-approaches-trends.png" class="img-fluid figure-img" alt="Line chart of outcome harvesting surface-mention counts by year, 2000-2025, a small series.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-participatory-and-agency-based-approaches-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Participatory and agency-based approaches: surface-mention publications by year, 2000–2025. Data: OpenAlex, retrieved 2 August 2026.
</figcaption>
</figure>
</div>
<p>Two contrasts stand out. First, agent-based modelling and system dynamics (<a href="appendix-supporting-simulation.html" class="quarto-xref"><span>Chapter 23</span></a>) each generate far more surface mentions than any core method family, consistent with their use across engineering, economics, and computer science well beyond programme evaluation; <a href="11-simulation.html" class="quarto-xref"><span>Chapter 13</span></a> reads this as a reason for restraint rather than a claim about evaluation use. Second, diagnostic and participatory approaches remain small throughout the period even as their corpora grow proportionally: Bayesian process tracing reached 29 pairs and outcome harvesting 64 pairs by 2025, against several thousand for qualitative comparative analysis, process tracing, and realist evaluation. A small corpus is more sensitive to a handful of publications and supports a correspondingly narrower claim about the shape of its trend.</p>
</section>
<section id="where-the-work-is-produced" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="where-the-work-is-produced"><span class="header-section-number">5.5.3</span> Where the work is produced</h3>
<p><a href="#fig-family-institution-country-shares" class="quarto-xref">Figure&nbsp;<span>5.7</span></a> reports the institutional-country share of each family’s fractional method–work count. Every family has a substantial United States share, but the next-largest contributor differs sharply: China for configurational approaches (reflecting a large qualitative comparative analysis literature in management and engineering fields), the United Kingdom and Australia for counterfactual designs, the United Kingdom for generative and mechanistic approaches (consistent with the concentration of realist evaluation in UK health-services research), and a thin, geographically scattered set of secondary contributors for diagnostic and participatory approaches, whose corpora are too small to support a stable ranking beyond the leading country.</p>
<div id="fig-family-institution-country-shares" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Heatmap of institutional country shares by method family. The United States leads every family. China is the second-largest contributor for configurational approaches; the United Kingdom is the second-largest contributor for counterfactual designs and for generative and mechanistic approaches.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-family-institution-country-shares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/bibliometrics_intent_v2/fig-family-institution-country-shares.png" class="img-fluid figure-img" alt="Heatmap of institutional country shares by method family. The United States leads every family. China is the second-largest contributor for configurational approaches; the United Kingdom is the second-largest contributor for counterfactual designs and for generative and mechanistic approaches.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-family-institution-country-shares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: Institutional-country share of each method family’s fractional method–work count, 2000–2025. Values use fractional authorship credit; missing affiliations are excluded from this figure. Data: OpenAlex, retrieved 2 August 2026.
</figcaption>
</figure>
</div>
</section>
<section id="overlap-between-families" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="overlap-between-families"><span class="header-section-number">5.5.4</span> Overlap between families</h3>
<p><a href="13-integration.html" class="quarto-xref"><span>Chapter 15</span></a> reports title-and-abstract co-mention between the five core method families (<a href="13-integration.html#fig-co-occurrence" class="quarto-xref">Figure&nbsp;<span>15.1</span></a>). The result is summarised here because it bears on how the map should be read: explicit co-mention is rare, with the only material overlap between configurational and generative and mechanistic approaches (101 works, a Jaccard coefficient of 0.62 per cent), and no other family pair exceeding 0.02 per cent. The discovery corpus therefore describes five largely separate literatures that happen to converge on a shared inferential logic, not a single integrated field. <a href="13-integration.html" class="quarto-xref"><span>Chapter 15</span></a> explains why this absence of visible co-mention does not itself establish that evaluators fail to combine these methods in practice.</p>
</section>
</section>
<section id="sec-methods-reproducibility" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-methods-reproducibility"><span class="header-section-number">5.6</span> Reproducibility</h2>
<p><code>fetch_references.py</code> records the date range, API fields, exact queries, OpenAlex result counts, retrieved counts, completion status, page counts, file names, and SHA-256 hashes in <code>retrieval_manifest.json</code>. It also writes a checkpoint after every page so an interrupted search can resume from its last confirmed cursor. <code>screen_references.py</code> produces the work, work–method, author–institution, filter-audit, and validation files together with <code>corpus_manifest.json</code>. <code>analyse_bibliometrics.py</code> records the unit and definition of every derived table in <code>analysis_manifest.json</code>.</p>
<p>The manifests distinguish a successful script run from a complete analysis corpus. Downstream scripts reject a capped or interrupted retrieval unless the user explicitly enables an incomplete test run. The analysis files used for publication must come from a complete retrieval, a completed validation file where application claims are made, and a recorded version of the code and search configuration.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The complete August 2026 raw archive replaces the capped May 2026 corpus. It records publications that name a configured expression in the title or abstract. The two-stage review shows that several expressions have substantial false-match rates. The 28,687 keyword-flagged pairs must not be reported as evaluated applications, and neither the core-method surface counts nor the co-mention matrix measures method adoption or integration.</p>
</div>
</div>
</section>
<section id="sec-methods-limits" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-methods-limits"><span class="header-section-number">5.7</span> Limitations</h2>
<p>OpenAlex does not provide complete coverage of donor reports, consultancy outputs, internal evaluations, and other grey literature. The application subset will therefore describe indexed publications rather than the population of development evaluations. Searches based on named expressions miss studies that use a procedure without applying its standard label, while ambiguous expressions can retrieve unrelated work. Manual validation estimates the latter problem but cannot measure studies that the search never retrieved.</p>
<p>Bibliographic metadata also change over time. OpenAlex may update abstracts, topics, affiliations, citation counts, and author disambiguation after the retrieval date. The manifests make a given analysis reproducible from the saved data, but a later API query need not return identical metadata. Trend analyses therefore report the retrieval date and avoid interpreting small year-to-year differences as changes in practice.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-openalex2026" class="csl-entry" role="listitem">
OpenAlex. (2026). <em>OpenAlex API documentation: works</em>. <a href="https://developers.openalex.org/api-reference/works">https://developers.openalex.org/api-reference/works</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-eight-logics.html" class="pagination-link" aria-label="Causal Reasoning in Small-n Evaluation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Causal Reasoning in Small-n Evaluation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-counterfactual.html" class="pagination-link" aria-label="Counterfactual Designs for Small Samples">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Counterfactual Designs for Small Samples</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>